apply plugin: 'maven-publish'
apply plugin: 'org.jetbrains.dokka'
tasks.register('androidJavadocJar', Jar) {
    archiveClassifier.set('javadoc')
    from tasks.named('dokkaGeneratePublicationHtml').flatMap { it.outputDirectory }
}



tasks.register('androidSourcesJar', Jar) {

    archiveClassifier.set('sources')

    if (project.plugins.findPlugin('com.android.library')) {

        from android.sourceSets.main.java.srcDirs
        from android.sourceSets.main.kotlin.srcDirs

    } else {

        from sourceSets.main.java.srcDirs
        from sourceSets.main.kotlin.srcDirs
    }
}


artifacts {
    archives tasks.named('androidSourcesJar')
}


group = PUBLISH_GROUP_ID
version = PUBLISH_VERSION


afterEvaluate {

    publishing {

        publications {

            release(MavenPublication) {

                groupId = PUBLISH_GROUP_ID
                artifactId = PUBLISH_ARTIFACT_ID
                version = PUBLISH_VERSION

                if (project.plugins.findPlugin('com.android.library')) {
                    from components.release
                }


                artifact tasks.named('androidSourcesJar')
                artifact tasks.named('androidJavadocJar')


                pom {

                    name = 'ComposeNeumorphism'

                    description =
                            'A Neumorphism UI library for Jetpack Compose and Android Views.'

                    url =
                            'https://github.com/obieda-hussien/neumorphic-compose-pro'


                    licenses {

                        license {

                            name =
                                    'Apache License, Version 2.0'

                            url =
                                    'https://www.apache.org/licenses/LICENSE-2.0.txt'
                        }
                    }


                    developers {

                        developer {

                            id = 'obieda-hussien'
                            name = 'Obieda Hussien'
                        }
                    }


                    scm {

                        connection =
                                'scm:git:git://github.com/obieda-hussien/neumorphic-compose-pro.git'

                        developerConnection =
                                'scm:git:ssh://github.com/obieda-hussien/neumorphic-compose-pro.git'

                        url =
                                'https://github.com/obieda-hussien/neumorphic-compose-pro'
                    }
                }
            }
        }
    }
}


// Central signing uses an in-memory key; JitPack builds need no credentials.
apply plugin: 'signing'
def centralSigningKey = providers.environmentVariable('SIGNING_KEY').orNull
def centralSigningPassword = providers.environmentVariable('SIGNING_PASSWORD').orNull
if (centralSigningKey) {
    signing {
        useInMemoryPgpKeys(centralSigningKey, centralSigningPassword)
        sign publishing.publications
    }
}
publishing {
    repositories {
        maven {
            name = 'CentralStaging'
            url = rootProject.layout.buildDirectory.dir('central-staging')
        }
    }
}
